service: python-service

provider:
  name: openwhisk
  runtime: python

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
  bookSearch:
    handler: book_search.search
    events:
      - http:
          path: ping
          method: get
    annotations:
      web-export: true
  getBookList:
    handler: book_list.getBookList
    events: 
      - http:
          path: ping
          method: get
    annotations:
      web-export: true

plugins:
  - serverless-openwhisk

db_conn_string: ${DATABASE=BLUDB;HOSTNAME=dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net;PORT=50001;PROTOCOL=TCPIP;UID=kxj28592;PWD=7d^3h26x21fr717n;Security=SSL;}

