service: python-service

provider:
  name: openwhisk
  runtime: python

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
  bookSearch:
    handler: book_search.search
    events:
      - http:
        path: ping
        method: get
    annotations:
      web-export: true

plugins:
  - serverless-openwhisk

